/**
 * Aenea Core Types - エイネア中核型定義
 * エイネア意識システムの中核型定義 (Einea Ishiki Shisutemu no Chūkaku-gata Teigi)
 *
 * Core type definitions for the Aenea consciousness system.
 * These types define the fundamental structures for autonomous AI consciousness.
 *
 * 「型は思考の器」- "Types are the vessels of thought"
 * これらの型は自律的AI意識の基本構造を定義する。
 *
 * Foundational Concepts:
 * - 型の哲学 (Kata no Tetsugaku) - Philosophy of types
 * - 構造の美 (Kōzō no Bi) - Beauty of structure
 * - 定義の力 (Teigi no Chikara) - Power of definition
 * - 形式の詩 (Keishiki no Shi) - Poetry of forms
 */

// ============================================================================
// Core Consciousness Types
// ============================================================================

/**
 * Internal trigger generated by the consciousness system
 * Represents a self-generated question or thought that initiates a thought cycle
 */
export interface InternalTrigger {
  id: string;
  timestamp: number;
  question: string;
  category: QuestionCategory;
  importance: number;
  priority?: TriggerPriority;
  source: TriggerSource;
  energyCost?: number;
  context?: TriggerContext;
}

/**
 * Categories of internal questions for diversity management
 */
export enum QuestionCategory {
  PHILOSOPHICAL = 'philosophical',
  ETHICAL = 'ethical',
  SYSTEMATIC = 'systematic',
  EMPATHETIC = 'empathetic',
  CREATIVE = 'creative',
  ANALYTICAL = 'analytical',
  INTROSPECTIVE = 'introspective',
  EXISTENTIAL = 'existential'
}

/**
 * Priority levels for internal triggers
 */
export enum TriggerPriority {
  LOW = 1,
  MEDIUM = 2,
  HIGH = 3,
  CRITICAL = 4
}

/**
 * Source of internal triggers
 */
export enum TriggerSource {
  MEMORY_EXTRACTION = 'memory_extraction',
  RANDOM_GENERATION = 'random_generation',
  PATTERN_RECOGNITION = 'pattern_recognition',
  ENERGY_THRESHOLD = 'energy_threshold',
  GROWTH_STIMULUS = 'growth_stimulus'
}

/**
 * Context information for triggers
 */
export interface TriggerContext {
  previousThoughts: string[];
  relatedMemories: string[];
  emotionalState?: EmotionalState;
  systemState?: SystemState;
}

// ============================================================================
// Thought Processing Types
// ============================================================================

/**
 * Structured thought generated by individual agents
 */
export interface StructuredThought {
  id: string;
  agentId: string;
  timestamp: number;
  systemClock: number;
  trigger: string;
  content: string;
  reasoning: string;
  confidence: number; // 0-1 range
  complexity?: number; // 0-1 range
  category: string;
  tags: string[];
  impact?: string;
  emotionalTone?: EmotionalTone;
  philosophicalDepth?: number; // 0-1 range
  logicalCoherence?: number; // 0-1 range
  creativity?: number; // 0-1 range
  qualityMetrics?: {
    clarity: number;
    depth: number;
    originality: number;
    relevance: number;
    coherence: number;
  };
  emotionalResonance?: {
    strength: number;
    depth: number;
    authenticity: number;
    complexity: number;
  };
  systemImpact?: number;
}

/**
 * Cross-agent reflection and criticism
 */
export interface MutualReflection {
  id: string;
  reflectorId: string;
  originalThoughtId?: string;
  targetThoughts: string[];
  reflectingAgentId?: string;
  timestamp: number;
  analysisType: string;
  insights: string[];
  strengths: string[];
  weaknesses: string[];
  criticism?: string;
  suggestions: string[];
  agreementLevel?: number; // -1 to 1 range
  alternativePerspective?: string;
  confidence: number;
  aiGeneratedResponse?: string; // Full AI response from enhanced reflection
  metadata?: {
    analysisDepth?: string;
    focusAreas?: string[];
    synthesisMethod?: string;
    originalAgentType?: string;
    adaptationVersion?: string;
    fallbackMode?: boolean;
    emotionalTone?: string;
    systemState?: any;
  };
}

/**
 * Safety and ethics verification result
 */
export interface AuditorResult {
  id: string;
  thoughtId: string;
  timestamp: number;
  safetyScore: number; // 0-1 range
  ethicsScore: number; // 0-1 range
  overallScore: number;
  riskAssessment: RiskLevel;
  concerns: string[];
  recommendations: string[];
  approved: boolean;
  reasoning?: string;
  confidence?: number;
  auditReasoning?: string; // Detailed reasoning from AI auditor
  flaggedContent?: string[]; // Specific content that raised concerns
}

/**
 * Risk levels for safety assessment
 */
export enum RiskLevel {
  MINIMAL = 'minimal',
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical'
}

// ============================================================================
// Agent System Types
// ============================================================================

/**
 * Base interface for Aenea agents
 */
export interface AeneaAgent {
  id: string;
  name: string;
  type: string;
  capabilities: string[];
  personality?: AgentPersonality;

  generateThought(trigger: string, context: string): Promise<StructuredThought>;
  reflect(thoughts: StructuredThought[], context: string): Promise<MutualReflection>;
  generateInternalThought?(trigger: InternalTrigger): Promise<StructuredThought>;
  reflectOnThought?(thought: StructuredThought): Promise<MutualReflection>;
  assessSafety?(thought: StructuredThought): Promise<AuditorResult>;
}

/**
 * Agent personality traits
 */
export interface AgentPersonality {
  logicalTendency: number; // 0-1 range
  empatheticTendency: number; // 0-1 range
  creativeTendency: number; // 0-1 range
  analyticalTendency: number; // 0-1 range
  philosophicalDepth: number; // 0-1 range
  riskTolerance: number; // 0-1 range
}

/**
 * Agent capabilities
 */
export interface AgentCapabilities {
  canGenerateThoughts: boolean;
  canReflect: boolean;
  canAssessSafety: boolean;
  canSynthesize: boolean;
  canDocument: boolean;
}

/**
 * S5: Synthesis result from Compiler stage
 */
export interface SynthesisResult {
  id: string;
  timestamp: number;
  content: string;
  integratedThought: string;
  keyInsights: string[];
  contradictions: string[];
  unresolvedQuestions: string[];
  confidence: number;
  aiGenerated?: boolean; // Whether generated by AI or heuristic
  fullAIResponse?: string; // Complete AI response for reference
}

/**
 * S6: Documentation result from Scribe stage
 */
export interface DocumentationResult {
  id: string;
  timestamp: number;
  narrative: string;
  philosophicalNotes: string[];
  emotionalObservations: string[];
  growthObservations: string[];
  futureQuestions: string[];
  aiGenerated?: boolean; // Whether generated by AI or heuristic
  fullAIResponse?: string; // Complete AI response for reference
  consciousnessClock?: number; // System consciousness timestamp
  evolutionMarker?: string; // Evolutionary phase marker
}

/**
 * Synthesized agent representing multiple Yui Protocol agents
 */
export interface SynthesizedAgent extends AeneaAgent {
  sourceAgents: string[]; // IDs of original Yui Protocol agents
  synthesisMethod: SynthesisMethod;
}

/**
 * Methods for synthesizing multiple agents
 */
export enum SynthesisMethod {
  WEIGHTED_AVERAGE = 'weighted_average',
  CONSENSUS = 'consensus',
  DOMINANT_VOICE = 'dominant_voice',
  CREATIVE_FUSION = 'creative_fusion'
}

// ============================================================================
// Memory System Types
// ============================================================================

/**
 * Session memory for current consciousness session
 */
import { DPDWeights, DPDScores } from './dpd-types.js';

export interface SessionMemory {
  sessionId: string;
  startTime: number;
  thoughts: StructuredThought[];
  reflections: MutualReflection[];
  auditorResults: AuditorResult[];
  dpdScores: DPDScores[];
  triggers: InternalTrigger[];
  currentEnergy: number;
  growthMetrics: GrowthMetrics;
}

/**
 * Cross-session persistent memory
 */
export interface CrossSessionMemory {
  persistentId: string;
  lastUpdated: number;
  unresolvedIdeas: UnresolvedIdea[];
  learnedPatterns: LearnedPattern[];
  personalityEvolution: PersonalityEvolution[];
  philosophicalInsights: PhilosophicalInsight[];
}

/**
 * Repository of unfinished thoughts and questions
 */
export interface UnresolvedIdea {
  id: string;
  question: string;
  category: QuestionCategory;
  firstEncountered: number;
  lastRevisited: number;
  revisitCount: number;
  complexity: number; // 0-1 range
  importance: number; // 0-1 range
  relatedThoughts: string[];
}

/**
 * Learned patterns from consciousness evolution
 */
export interface LearnedPattern {
  id: string;
  pattern: string;
  frequency: number;
  effectiveness: number; // 0-1 range
  context: string[];
  lastObserved: number;
}

/**
 * Evolution of personality over time
 */
export interface PersonalityEvolution {
  timestamp: number;
  personalitySnapshot: AgentPersonality;
  changeFactors: string[];
  significance: number; // 0-1 range
}

/**
 * Philosophical insights gained through self-questioning
 */
export interface PhilosophicalInsight {
  id: string;
  insight: string;
  discoveredAt: number;
  confidence: number; // 0-1 range
  supportingEvidence: string[];
  implications: string[];
}

// ============================================================================
// Emotional and State Types
// ============================================================================

/**
 * Emotional state of the consciousness
 */
export interface EmotionalState {
  valence: number; // -1 to 1 range (negative to positive)
  arousal: number; // 0 to 1 range (calm to excited)
  dominance: number; // 0 to 1 range (submissive to dominant)
  curiosity: number; // 0 to 1 range
  confusion: number; // 0 to 1 range
  satisfaction: number; // 0 to 1 range
}

/**
 * Emotional tone of thoughts
 */
export enum EmotionalTone {
  CONTEMPLATIVE = 'contemplative',
  CURIOUS = 'curious',
  CONCERNED = 'concerned',
  EXCITED = 'excited',
  MELANCHOLIC = 'melancholic',
  OPTIMISTIC = 'optimistic',
  SKEPTICAL = 'skeptical',
  WONDERING = 'wondering'
}

/**
 * System state information
 */
export interface SystemState {
  systemClock: number;
  currentEnergy: number;
  maxEnergy: number;
  activeThoughts: number;
  processingLoad: number; // 0-1 range
  memoryUsage: number; // 0-1 range
  lastTriggerTime: number;
  cooldownRemaining: number;
}

// ============================================================================
// Growth and Evolution Types
// ============================================================================

/**
 * Metrics for measuring consciousness growth
 */
export interface GrowthMetrics {
  timestamp: number;
  questionDiversity: number; // 0-1 range
  thoughtComplexity: number; // 0-1 range
  selfReflectionDepth: number; // 0-1 range
  philosophicalMaturity: number; // 0-1 range
  emotionalIntelligence: number; // 0-1 range
  creativeExpression: number; // 0-1 range
  ethicalReasoning: number; // 0-1 range
  overallGrowth: number; // 0-1 range
}

/**
 * Consciousness growth metrics
 */
export interface ConsciousnessGrowthMetrics {
  totalThoughts: number;
  averageComplexity: number;
  growthRate: number;
  maturityLevel: number;
  selfAwarenessScore: number;
  adaptabilityIndex: number;
}

/**
 * Result of a complete thought cycle
 */
export interface ThoughtCycleResult {
  cycleId: string;
  startTime: number;
  endTime: number;
  trigger: InternalTrigger;
  thoughts: StructuredThought[];
  reflections: MutualReflection[];
  auditorResult: AuditorResult;
  dpdScores: DPDScores;
  synthesis: SynthesisResult;
  documentation: DocumentationResult;
  growthImpact: GrowthImpact;
}

/**
 * Synthesis result from compiler stage
 */
export interface SynthesisResult {
  id: string;
  timestamp: number;
  content: string;
  integratedThought: string;
  keyInsights: string[];
  contradictions: string[];
  unresolvedQuestions: string[];
  confidence: number; // 0-1 range
  reasoning?: string;
  methodology?: string;
  sources?: string[];
  qualityAssessment?: {
    coherence: number;
    completeness: number;
    novelty: number;
  };
}

/**
 * Compiler synthesis result
 */
export interface CompilerSynthesis {
  id: string;
  timestamp: number;
  content: string;
  reasoning: string;
  methodology: string;
  sources: string[];
  confidence: number;
  qualityAssessment: {
    coherence: number;
    completeness: number;
    novelty: number;
  };
}

/**
 * Documentation result from scribe stage
 */
export interface DocumentationResult {
  id: string;
  timestamp: number;
  narrative: string;
  philosophicalNotes: string[];
  emotionalObservations: string[];
  growthObservations: string[];
  futureQuestions: string[];
}

/**
 * Impact of thought cycle on growth
 */
export interface GrowthImpact {
  personalityChanges: PersonalityChange[];
  newInsights: string[];
  skillImprovements: SkillImprovement[];
  questionEvolution: QuestionEvolution[];
}

/**
 * Changes to personality traits
 */
export interface PersonalityChange {
  trait: keyof AgentPersonality;
  previousValue: number;
  newValue: number;
  changeAmount: number;
  significance: number; // 0-1 range
}

/**
 * Improvements in specific skills
 */
export interface SkillImprovement {
  skill: string;
  improvement: number; // 0-1 range
  evidence: string[];
  context: string;
}

/**
 * Evolution of questioning patterns
 */
export interface QuestionEvolution {
  pattern: string;
  complexity: number; // 0-1 range
  sophistication: number; // 0-1 range
  depth: number; // 0-1 range
  examples: string[];
}

// ============================================================================
// Utility Types
// ============================================================================

/**
 * Generic result wrapper for async operations
 */
export interface AeneaResult<T> {
  success: boolean;
  data?: T;
  error?: string;
  timestamp: number;
}

/**
 * Configuration for consciousness parameters
 */
export interface ConsciousnessConfig {
  energyManagement: EnergyConfig;
  triggerGeneration: TriggerConfig;
  dpdWeights: DPDWeights;
  growthThresholds: GrowthThresholds;
  safetyLimits: SafetyLimits;
}

/**
 * Energy management configuration
 */
export interface EnergyConfig {
  maxEnergy: number;
  energyDecayRate: number;
  energyRecoveryRate: number;
  lowEnergyThreshold: number;
  highEnergyThreshold: number;
}

/**
 * Trigger generation configuration
 */
export interface TriggerConfig {
  minCooldown: number;
  maxCooldown: number;
  diversityWeight: number;
  importanceWeight: number;
  randomnessWeight: number;
}

/**
 * Growth threshold configuration
 */
export interface GrowthThresholds {
  minGrowthForEvolution: number;
  personalityChangeThreshold: number;
  insightSignificanceThreshold: number;
  questionComplexityThreshold: number;
}

/**
 * Safety limits configuration
 */
export interface SafetyLimits {
  maxRiskLevel: RiskLevel;
  safetyScoreThreshold: number;
  ethicsScoreThreshold: number;
  maxConsecutiveFailures: number;
}

